name: Deploy frontend to Azure Static Web App via Azure CLI

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Build React App
        run: |
          cd frontend
          npm install
          npm run build

      - name: Azure Login with OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
      - name: Publish upload_function
        run: |
          cd backend/upload_function
          zip -r function.zip .
          az functionapp deployment source config-zip \
            --resource-group rg-transcriber \
            --name upload-transcriber \
            --src function.zip
          cd ../..

      - name: Get upload_function URL
        id: get-func-url
        run: |
          url=$(az functionapp show \
            --resource-group rg-transcriber \
            --name upload-transcriber \
            --query "defaultHostName" -o tsv)
          echo "API_URL=https://$url/api/upload" >> $GITHUB_ENV

      - name: "Get and Mask SWA Token"
        uses: azure/CLI@v1
        with:
          inlineScript: |
            token=$(az staticwebapp secrets list -n frontend-transcriber | jq -r '.properties.apiKey')
            echo "::add-mask::$token"
            echo "SWA_TOKEN=$token" >> $GITHUB_ENV

      - name: Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ env.SWA_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "frontend/build"
          skip_app_build: true
          env: |
            VITE_API_URL=${{ env.API_URL }}
